# -*- coding: utf-8 -*-
# Copyright 2020 Kevin Schlosser

# HVAC commands

HEAT_SET_POINT_TEMPERATURE_MODIFY = 0x01  # HVAC, ZONE, WATER
COOL_SET_POINT_TEMPERATURE_MODIFY = 0x02  # HVAC, ZONE
HEAT_PROFILE_CHANGE = 0x03  # HVAC, ZONE, WATER
COOL_PROFILE_CHANGE = 0x04  # HVAC, ZONE
SYSTEM_SWITCH_MODIFY = 0x05  # HVAC, ZONE, WATER
PERMANENT_SET_POINT_TEMP_HOLD_MODIFY = 0x06  # HVAC, ZONE
FAN_KEY_SELECTION = 0x07  # HVAC
HVAC_HOLD_OVERRIDE = 0x08  # HVAC, ZONE
BEEPER_ENABLE = 0x09  # HVAC
FAHRENHEIT_CELSIUS_DISPLAY = 0x0C  # HVAC, WATER
COMFORT_RECOVERY_MODIFY = 0x0E  # HVAC
REAL_TIME_DAY_OVERRIDE = 0x0F  # HVAC, ZONE, WATER
CHANGE_FILTER_TIME_REMAINING = 0x14  # HVAC, ZONE
VACATION_MODE = 0x15  # HVAC, WATER
HIGH_ALARM_LIMIT_CHANGE = 0x16  # HVAC, WATER
LOW_ALARM_LIMIT_CHANGE = 0x17  # HVAC, WATER
HIGH_OUTDOOR_ALARM_LIMIT_CHANGE = 0x18  # HVAC
LOW_OUTDOOR_ALARM_LIMIT_CHANGE = 0x19  # HVAC
TEMP_DISPLAY_ADJ_FACTOR_CHANGE = 0x1A  # HVAC
CLEAR_COMPRESSOR_RUN_TIME = 0x2D  # HVAC
RESET_MICRO = 0x31  # HVAC, WATER
COMPRESSOR_LOCKOUT = 0x33  # HVAC
HOLD_RELEASE = 0x3D  # HVAC
PROGRAM_INTERVAL_TYPE_MODIFICATION = 0x3E  # HVAC, WATER
COMMUNICATIONS_RECEIVER_ON_OFF = 0x3F  # HVAC, WATER
FORCE_PHONE_NUMBER_DISPLAY = 0x40  # HVAC, WATER
RESTORE_FACTORY_DEFAULTS = 0x45  # HVAC, ZONE, WATER
CUSTOM_MESSAGE_AREA_DISPLAY_DATA = 0x46  # HVAC
SET_POINT_TEMP_AND_TEMPORARY_HOLD = 0x47  # HVAC
CONTINUOUS_DISPLAY_LIGHT = 0x48  # HVAC
ADVANCE_REAL_TIME_DAY_OVERRIDE = 0x4E  # HVAC
KEYPAD_LOCKOUT = 0x4F  # HVAC, WATER
TEST_MODE = 0x50  # HVAC, ZONE, WATER
SUBSYSTEM_INSTALLATION_TEST = 0x51  # HVAC, ZONE, WATER
AUTO_PAIRING_REQUEST = 0x52  # ZONE
PAIRING_OWNERSHIP_REQUEST = 0x53  # ZONE

SET_POINT_TEMP_TIME_HOLD = 0x53  # HVAC
COMFORT_MODE_MODIFICATION = 0x55  # HVAC
LIMITED_HEAT_AND_COOL_RANGE = 0x56  # HVAC
AUTO_PAIRING_REQUEST = 0x57  # HVAC, ZONE
PAIRING_OWNERSHIP_REQUEST = 0x58  # HVAC, ZONE
HVAC_REVERSING_VALVE_CONFIG = 0x59  # HVAC
HVAC_HUM_DEHUM_CONFIG = 0x5A  # HVAC
HVAC_CHANGE_UV_LIGHT_MAINTENANCE_TIMER = 0x5B  # HVAC, ZONE
HVAC_CHANGE_HUMIDIFIER_PAD_MAINT_TIMERALL = 0x5C  # HVAC, ZONE


DEHUMIDIFICATION_SET_POINT_MODIFY = 0x5D  # ZONE
HUMIDIFICATION_SET_POINT_MODIFY = 0x5E  # ZONE

HVAC_DAMPER_CLOSURE_POSITION_DEMAND = 0x60  # HVAC, ZONE

ZONE_SUBSYSTEM_BUSY_STATUS = 0x61
HVAC_SUBSYSTEM_BUSY_STATUS = 0x61

ZONE_DEHUMIDIFICATION_DEMAND = 0x62
HVAC_DEHUMIDIFICATION_DEMAND = 0x62


ZONE_HUMIDIFICATION_DEMAND = 0x63
HVAC_HUMIDIFICATION_DEMAND = 0x63


ZONE_HEAT_DEMAND = 0x64
HVAC_HEAT_DEMAND = 0x64

ZONE_COOL_DEMAND = 0x65
HVAC_COOL_DEMAND = 0x65


ZONE_FAN_DEMAND = 0x66
HVAC_FAN_DEMAND = 0x66


ZONE_BACK_UP_HEAT_DEMAND = 0x67
HVAC_BACK_UP_HEAT_DEMAND = 0x67


ZONE_DEFROST_DEMAND = 0x68
HVAC_DEFROST_DEMAND = 0x68

ZONE_AUX_HEAT_DEMAND = 0x69
HVAC_AUX_HEAT_DEMAND = 0x69



# MOTOR PROFILE
SET_MOTOR_SPEED = 0x6A  # INDOOR*, INDUCER*, OUTDOOR*
SET_MOTOR_TORQUE = 0x6B  # INDOOR*
SET_AIRFLOW_DEMAND = 0x6C  # INDOOR*
SET_MODE = 0x6D  # INDOOR*, INDUCER*, OUTDOOR*
SET_DEMAND_RAMP_RATE = 0x6E  # INDOOR*, OUTDOOR*
SET_MOTOR_DIRECTION = 0x6F  # INDOOR*, INDUCER*, OUTDOOR*
SET_MOTOR_TORQUE_PERCENT = 0x70  # INDOOR*
SET_MOTOR_POSITION_DEMAND = 0x71  # STEPPER*
SET_BLOWER_COEFFICIENT_1 = 0x72  # INDOOR*
SET_BLOWER_COEFFICIENT_2 = 0x73  # INDOOR*
SET_BLOWER_COEFFICIENT_3 = 0x74  # INDOOR*
SET_BLOWER_COEFFICIENT_4 = 0x75  # INDOOR*
SET_BLOWER_COEFFICIENT_5 = 0x76  # INDOOR*
SET_BLOWER_IDENTIFICATION_0 = 0x77
SET_BLOWER_IDENTIFICATION_1 = 0x78
SET_BLOWER_IDENTIFICATION_2 = 0x79
SET_BLOWER_IDENTIFICATION_3 = 0x7A
SET_BLOWER_IDENTIFICATION_4 = 0x7B
SET_BLOWER_IDENTIFICATION_5 = 0x7C
SET_SPEED_LIMIT = 0x7F  # INDUCER*
SET_TORQUE_LIMIT = 0x80
SET_AIRFLOW_LIMIT = 0x81  # INDOOR*
SET_POWER_OUTPUT_LIMIT = 0x82
SET_DEVICE_TEMPERATURE_LIMIT = 0x83
STOP_MOTOR_BY_BRAKING = 0x85
RUN_STOP_MOTOR = 0x86  # INDOOR*, INDUCER*, OUTDOOR*
SET_DEMAND_RAMP_TIME = 0x88
SET_INDUCER_RAMP_RATE = 0x89  # INDUCER*
SET_BLOWER_COEFFICIENT_6 = 0x8A
SET_BLOWER_COEFFICIENT_7 = 0x8B
SET_BLOWER_COEFFICIENT_8 = 0x8C
SET_BLOWER_COEFFICIENT_9 = 0x8D
SET_BLOWER_COEFFICIENT_10 = 0x8E


PUBLISH_PRICE = 0xE0  # HVAC, ZONE
WATER_HEATER_MODIFY = 0xF0

