# -*- coding: utf-8 -*-
# Copyright 2020 Kevin Schlosser


# CT-CIM Mapped Message Types

GET_CONFIGURATION = 0x01
GET_CONFIGURATION_RESPONSE = 0x81

GET_STATUS = 0x02
GET_STATUS_RESPONSE = 0x82

SET_CONTROL_COMMAND = 0x03
SET_CONTROL_COMMAND_RESPONSE = 0x83

SET_DISPLAY_MESSAGE = 0x04
SET_DISPLAY_MESSAGE_RESPONSE = 0x84

SET_DISGNOSTICS = 0x05
SET_DISGNOSTICS_RESPONSE = 0x85

GET_DIAGNOSTICS = 0x06
GET_DIAGNOSTICS_RESPONSE = 0x86

GET_SENSOR_DATA = 0x07
GET_SENSOR_DATA_RESPONSE = 0x87

SET_IDENTIFICATION = 0x0D
SET_IDENTIFICATION_RESPONSE = 0x8D

GET_IDENTIFICATION = 0x0E
GET_IDENTIFICATION_RESPONSE = 0x8E

SET_APPLICATION_SHARED_DATA_TO_NETWORK = 0x10
SET_APPLICATION_SHARED_DATA_TO_NETWORK_RESPONSE = 0x90

GET_APPLICATION_SHARED_DATA_TO_NETWORK = 0x11
GET_APPLICATION_SHARED_DATA_TO_NETWORK_RESPONSE = 0x91

SET_MANUFACTURER_DEVICE_DATA = 0x12
SET_MANUFACTURER_DEVICE_DATA_RESPONSE = 0x92

GET_MANUFACTURER_DEVICE_DATA = 0x13
GET_MANUFACTURER_DEVICE_DATA_RESPONSE = 0x93

SET_NETWORK_NODE_LIST = 0x14
SET_NETWORK_NODE_LIST_RESPONSE = 0x94

DIRECT_MEMORY_ACCESS_READ = 0x1D
DIRECT_MEMORY_ACCESS_READ_RESPONSE = 0x9D
DIRECT_MEMORY_ACCESS_READ_RESPONSE_MOTOR = 0x1E

SET_MANUFACTURER_GENERIC_DATA = 0x1F
SET_MANUFACTURER_GENERIC_DATA_RESPONSE = 0x9F

GET_MANUFACTURER_GENERIC_DATA = 0x20
GET_MANUFACTURER_GENERIC_DATA_RESPONSE = 0xA0
GET_MANUFACTURER_GENERIC_DATA_RESPONSE_MOTOR = 0x21

GET_USER_MENU = 0x41
GET_USER_MENU_RESPONSE = 0xC1

SET_USER_MENU = 0x42
SET_USER_MENU_RESPONSE = 0xC2

SET_FACTORY_SHARED_DATA_TO_APPLICATION = 0x43
SET_FACTORY_SHARED_DATA_TO_APPLICATION_RESPONSE = 0xC3

GET_SHARED_DATA_FROM_APPLICATION = 0x44
GET_SHARED_DATA_FROM_APPLICATION_RESPONSE = 0xC4

SET_ECHO_DATA = 0x5A
SET_ECHO_DATA_RESPONSE = 0xDA


# CT-485-specific Message Types

REQUEST_TO_RECEIVE = 0x00
REQUEST_TO_RECEIVE_RESPONSE = 0x00

NETWORK_STATE_REQUEST = 0x75
NETWORK_STATE_REQUEST_RESPONSE = 0xF5

ADDRESS_CONFIRMATION = 0x76
ADDRESS_CONFIRMATION_RESPONSE = 0xF6

TOKEN_OFFER = 0x77
TOKEN_OFFER_RESPONSE = 0xF7

VERSION_ANNOUNCEMENT = 0x78

NODE_DISCOVERY = 0x79
NODE_DISCOVERY_RESPONSE = 0xF9

SET_ADDRESS = 0x7A
SET_ADDRESS_RESPONSE = 0xFA

GET_NODE_ID = 0x7B
GET_NODE_ID_RESPONSE = 0xFB

NETWORK_SHARED_DATA_SECTOR_IMAGE_READ_WRITE_REQUEST = 0x7D
NETWORK_SHARED_DATA_SECTOR_IMAGE_READ_WRITE_REQUEST_RESPONSE = 0xFD

NETWORK_ENCAPSULATION_REQUEST = 0x7E
NETWORK_ENCAPSULATION_REQUEST_RESPONSE = 0xFE
