# -*- coding: utf-8 -*-
# Copyright 2020 Kevin Schlosser

# CT-CIM Mapped Message Types

from . import signal


class MessageType(int):
    
    def __init__(self, value):
        try:
            int.__init__(self, value)
        except TypeError:
            int.__init__(self)
    
    def connect(self, address, subnet, callback):
        signal.connect(self, address, subnet, callback)
        
    def disconnect(self, address, subnet):
        signal.disconnect(self, address, subnet)
        
    def send(self, packet):
        signal.send(self, packet)
        

GET_CONFIGURATION = MessageType(0x01)
GET_CONFIGURATION_RESPONSE = MessageType(0x81)

GET_STATUS = MessageType(0x02)
GET_STATUS_RESPONSE = MessageType(0x82)

SET_CONTROL_COMMAND = MessageType(0x03)
SET_CONTROL_COMMAND_RESPONSE = MessageType(0x83)

SET_DISPLAY_MESSAGE = MessageType(0x04)
SET_DISPLAY_MESSAGE_RESPONSE = MessageType(0x84)

SET_DISGNOSTICS = MessageType(0x05)
SET_DISGNOSTICS_RESPONSE = MessageType(0x85)

GET_DIAGNOSTICS = MessageType(0x06)
GET_DIAGNOSTICS_RESPONSE = MessageType(0x86)

GET_SENSOR_DATA = MessageType(0x07)
GET_SENSOR_DATA_RESPONSE = MessageType(0x87)

SET_IDENTIFICATION = MessageType(0x0D)
SET_IDENTIFICATION_RESPONSE = MessageType(0x8D)

GET_IDENTIFICATION = MessageType(0x0E)
GET_IDENTIFICATION_RESPONSE = MessageType(0x8E)

SET_APPLICATION_SHARED_DATA_TO_NETWORK = MessageType(0x10)
SET_APPLICATION_SHARED_DATA_TO_NETWORK_RESPONSE = MessageType(0x90)

GET_APPLICATION_SHARED_DATA_TO_NETWORK = MessageType(0x11)
GET_APPLICATION_SHARED_DATA_TO_NETWORK_RESPONSE = MessageType(0x91)

SET_MANUFACTURER_DEVICE_DATA = MessageType(0x12)
SET_MANUFACTURER_DEVICE_DATA_RESPONSE = MessageType(0x92)

GET_MANUFACTURER_DEVICE_DATA = MessageType(0x13)
GET_MANUFACTURER_DEVICE_DATA_RESPONSE = MessageType(0x93)

SET_NETWORK_NODE_LIST = MessageType(0x14)
SET_NETWORK_NODE_LIST_RESPONSE = MessageType(0x94)

DIRECT_MEMORY_ACCESS_READ = MessageType(0x1D)
DIRECT_MEMORY_ACCESS_READ_RESPONSE = MessageType(0x9D)
DIRECT_MEMORY_ACCESS_READ_RESPONSE_MOTOR = MessageType(0x1E)

SET_MANUFACTURER_GENERIC_DATA = MessageType(0x1F)
SET_MANUFACTURER_GENERIC_DATA_RESPONSE = MessageType(0x9F)

GET_MANUFACTURER_GENERIC_DATA = MessageType(0x20)
GET_MANUFACTURER_GENERIC_DATA_RESPONSE = MessageType(0xA0)
GET_MANUFACTURER_GENERIC_DATA_RESPONSE_MOTOR = MessageType(0x21)

GET_USER_MENU = MessageType(0x41)
GET_USER_MENU_RESPONSE = MessageType(0xC1)

SET_USER_MENU = MessageType(0x42)
SET_USER_MENU_RESPONSE = MessageType(0xC2)

SET_FACTORY_SHARED_DATA_TO_APPLICATION = MessageType(0x43)
SET_FACTORY_SHARED_DATA_TO_APPLICATION_RESPONSE = MessageType(0xC3)

GET_SHARED_DATA_FROM_APPLICATION = MessageType(0x44)
GET_SHARED_DATA_FROM_APPLICATION_RESPONSE = MessageType(0xC4)

SET_ECHO_DATA = MessageType(0x5A)
SET_ECHO_DATA_RESPONSE = MessageType(0xDA)


# CT-485-specific Message Types

REQUEST_TO_RECEIVE = MessageType(0x00)
REQUEST_TO_RECEIVE_RESPONSE = MessageType(0x00)

NETWORK_STATE_REQUEST = MessageType(0x75)
NETWORK_STATE_REQUEST_RESPONSE = MessageType(0xF5)

ADDRESS_CONFIRMATION = MessageType(0x76)
ADDRESS_CONFIRMATION_RESPONSE = MessageType(0xF6)

TOKEN_OFFER = MessageType(0x77)
TOKEN_OFFER_RESPONSE = MessageType(0xF7)

VERSION_ANNOUNCEMENT = MessageType(0x78)

NODE_DISCOVERY = MessageType(0x79)
NODE_DISCOVERY_RESPONSE = MessageType(0xF9)

SET_ADDRESS = MessageType(0x7A)
SET_ADDRESS_RESPONSE = MessageType(0xFA)

GET_NODE_ID = MessageType(0x7B)
GET_NODE_ID_RESPONSE = MessageType(0xFB)

NETWORK_SHARED_DATA_SECTOR_IMAGE_READ_WRITE_REQUEST = MessageType(0x7D)
NETWORK_SHARED_DATA_SECTOR_IMAGE_READ_WRITE_REQUEST_RESPONSE = MessageType(0xFD)

NETWORK_ENCAPSULATION_REQUEST = MessageType(0x7E)
NETWORK_ENCAPSULATION_REQUEST_RESPONSE = MessageType(0xFE)
